[project]
name = "rust-extension"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "purepani", email = "pani0028@umn.edu" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
rust-extension = "rust_extension:main"

[tool.maturin]
module-name = "rust_extension._core"
python-packages = ["rust_extension"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
